name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install app dependecies
        run: npm ci

      - name: Build
        run: npm run all

      - name: Lint
        run: npm run lint-check

      - name: Format
        run: npm run format-check

      - name: Run tests
        run: npm run test
