name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.deno
            ~/.cache/deno
            /opt/hostedtoolcache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        working-directory: src
        run: deno cache main.ts

      - name: Check format
        working-directory: src
        run: deno fmt --check

      - name: Lint
        working-directory: src
        run: deno lint

      - name: Get signing key
        run: |
          SIGNING_KEY=$(cat tests/assets/key_base64.txt)
          echo "SIGNING_KEY=${SIGNING_KEY}" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Sign APK and AAB
        uses: ./
        with:
          releaseDirectory: tests/assets
          signingKeyBase64: ${{ env.SIGNING_KEY }}
          output: signed
          alias: test_key
          keyStorePassword: android
          keyPassword: android